---
title: "PD1/TIM3/LAG3 Analysis"
header-includes: \usepackage{tabularx, longtable, graphicx, csquotes, hyperref, color}
output:
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    number_sections: yes
    toc: yes
always_allow_html: yes
geometry: margin=.7cm
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "fig/"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
})
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
set.seed(1)

library(knitr)
library(ggplot2)
library(gridExtra)
library(grid)
library(ggrepel)
library(cowplot)
library(rutils)
library(tidyr)
library(mclust)
library(reshape2)
library(data.tree)
library(networkD3)
library(limma)
library(edgeR)
library(RColorBrewer)
library(gplots)
library(WriteXLS)
library(xtable)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

l2 = load("../../TILsGBM/data/GBM_data.rda")
mat.GBM = countMat
pheno.GBM = Pheno
rm(list=l2)

l1 = load("../../TILsPRAD/obj/PCA_count_fpkm_matrices_processed.rda")
mat.PRAD = countMat
rm(list=l1)
l1 = load("../../TILsPRAD/obj/PCA_pheno.rda")
pheno.PRAD = pheno
colnames(pheno.PRAD)[7:8] = c("type", "status")
pheno.PRAD$sample = paste(pheno.PRAD$patient, pheno.PRAD$class, sep="_")
rm(list=l1)

l3 = load("../../TILsRCC/data/Kidney_data.rda")
mat.RCC = countMat
pheno.RCC = Pheno
rm(list=l3)

l4 = load("../../TILsBLCA/data/Bladder_data.rda")
mat.BLCA = countMat
pheno.BLCA = Pheno
rm(list=l4)


mat.list = list(GBM=mat.GBM,
                PRAD=mat.PRAD, 
                RCC=mat.RCC,
                BLCA=mat.BLCA)

pheno.list = list(GBM=pheno.GBM,
                  PRAD=pheno.PRAD,
                  RCC=pheno.RCC,
                  BLCA=pheno.BLCA)

# fix PRAD sample names
colnames(mat.list$PRAD) = pheno.list$PRAD[colnames(mat.list$PRAD), "sample"]

pal.default = c("#F8766D", "#619CFF", "#00BA38", "#C77CFF")
# red, blue, green
# active, naive, exp
 

```



```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}

# TUMOR_CD8_EXP - PBMC_CD8_ACTIVE

global_p_adj = function(tblist, method="BH"){
  P = lapply(tblist, function(x) x$P.Value)
  pv = Reduce(c, P)
  pv.adj = p.adjust(pv, method=method)
  j = 0
  for(i in 1:length(tblist)){
    a = j + 1
    b = length(P[[i]]) + j
    tblist[[i]]$adj.P.Val = pv.adj[a:b]
    j = b
  }
  tblist
}


table.list = lapply(names(pheno.list), function(tissue){

  x = mat.list[[tissue]]
  y = pheno.list[[tissue]]
  
  sel_exp = which(y$class == "TUMOR_CD8_EXP")
  sel_act = which(y$class == "PBMC_CD8_ACTIVE")
  
  x = x[, c(sel_exp, sel_act)]
  y = y[c(sel_exp, sel_act), ]
  
  y$class = factor(as.character(y$class))
  
  mod = model.matrix(~ 0 + patient + class, y)

  con = makeContrasts(group=classTUMOR_CD8_EXP, levels=mod)

  dge = DGEList(counts=x, group=y$class, remove.zeros=TRUE, genes=rownames(x))
  keep = rowSums(cpm(dge) > 1) >= 1
  dge = dge[keep, ]
  dge$samples$lib.size = colSums(dge$counts)

  dge_n = calcNormFactors(dge)

  V = voom(dge_n, mod, plot=FALSE)
  lmfit_voom = lmFit(V, mod)
  lmfit_con = contrasts.fit(lmfit_voom, contrasts=con)
  
  top_table = topTable(eBayes(lmfit_con), coef=1, number=Inf, adjust.method="bon")
    
  top_table = top_table[order(top_table$adj.P.Val, decreasing=FALSE), ]

  dt = decideTests(eBayes(lmfit_con), adjust.method="bon", method="global",lfc=1, p.value=0.05)
  
  list(table=top_table, dt=dt)

})
names(table.list) = names(pheno.list)

table.list.global = lapply(table.list, function(x) x$table)

table.list.global = global_p_adj(table.list.global, method="BH")
table.list.global = lapply(table.list.global, function(x) x[order(x$adj.P.Val), ])

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6, dev='png'}

venn.list = lapply(table.list.global, function(x) rownames(x)[which(x$adj.P.Val <= 0.00001)])

venn(venn.list)

int = Reduce(intersect, venn.list)

"METRNL" %in% int

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6, dev='png'}

mat.sign = sapply(table.list.global, function(x) sign(x[int, "logFC"]) )
# rowSums(mat.sign)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=12}

plot.list = lapply(table.list, function(x){
  
  T = x$table
  dt = x$dt

  df = data.frame(T, differential_expression=factor(dt[rownames(T), 1], levels=c(-1, 0, 1)),
                  label=rep(FALSE, nrow(T)))
  
  #df$label[1:min(20, sum(df$differential_expression != 0))] = TRUE
  df$label[which(df$gene %in% int)] = TRUE
  
  df$col = rep("black", nrow(df))
  df$col[df$label == TRUE & df$differential_expression == 1] = "darkred"
  df$col[df$label == TRUE & df$differential_expression == -1] = "darkblue"
  
  ggplot(df, aes(x=logFC, y=B, col=differential_expression, label=label))+
    geom_point(size=3, alpha=.8)+
    scale_color_manual(values=c("steelblue", "darkgray", "salmon"), 
                       breaks=c(-1, 1),
      labels=c(sprintf("logFC < -1, P < 0.05\n         (n=%d)\n", sum(df$differential_expression == -1)), 
                sprintf("logFC > 1, P < 0.05\n         (n=%d)", sum(df$differential_expression == 1)))
      )+
    geom_text_repel(data=subset(df, df$label == TRUE), 
                    aes(x=logFC, y=B, label=genes), 
            nudge_x=.1, nudge_y=0, color=df$col[df$label],
            show.legend=FALSE, fontface = 'bold')+
    ylim(min(df$B), max(df$B)+8)+
    xlab("logFC")+ylab("log Odds")+
    gtheme.GENERIC()+
    theme(legend.title=element_blank(),
          legend.position=c(.5, .9),
          legend.text = element_text(colour="grey20",size=12,angle=0,hjust=.5,vjust=0,face="plain"),
          legend.box.background=element_rect(fill=alpha("white", .9), size=10, color="white"))
    
})

```

```{r vol_GBM, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=12, dev='png'}

plot.list$GBM

```

```{r vol_PRAD, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=12, dev='png'}

plot.list$PRAD

```


```{r vol_RCC, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=12, dev='png'}

plot.list$RCC

```


```{r vol_BLCA, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=12, dev='png'}

plot.list$BLCA

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6, dev='png'}

save(table.list.global, file="obj/TUMOR_CD8_EXP_vs_PBMC_CD8_ACTIVE_contrasts.rda")

```


